minimumReleaseAge: 1440
minimumReleaseAgeExclude:
  - "@rollup/*"
onlyBuiltDependencies:
  - "@swc/core"
  - "esbuild"
  - "simple-git-hooks"
  - "workerd"
strictDepBuilds: true
trustPolicy: no-downgrade
